# Gradle Properties
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Mod Properties
version = 0.9.1
maven_group = com.periut
archives_base_name = accessoryapi

# Dependencies
retroapi_version = 0.2.0
gcapi_version = 3.3.0+gen2
retrocommands_version = 0.7.4
starac_version = 1.2.2+mcb1.7.3+gen2

# Ornithe Related Dependencies - check https://ornithemc.net/develop for the latest versions
minecraft_version = b1.7.3
loader_version = 0.19.3

biny_mappings = 9859f76
client_raven_build = 2
server_raven_build = 2
client_sparrow_build = 2
server_sparrow_build = 2
biny_nests_build = 2

osl_version = 0.18.0
