---
name: "Build and publish"

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/libs/*.jar

  publish:
    name: "Publish"
    needs: "build"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build/libs
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          files: build/libs/!(*-@(dev|sources|javadoc)).jar
          game-version-filter: betas

          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-game-versions: b1.7.3
          modrinth-id: ${{ vars.MODRINTH_ID }}
          loaders: babric fabric

          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-files: |
            build/libs/!(*-@(dev|sources|javadoc)).jar
            build/libs/*-@(dev|sources|javadoc).jar
